/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Staff;

import javax.swing.JOptionPane;
import models.Staff;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.ResultSet; 
import java.sql.Connection;
import models.kk;
/**
 *
 * @author ASUS
 */
public class Tambah extends javax.swing.JFrame {

    private Staff staff;

    /**
     * Creates new form Tambah
     */
    public Tambah(Staff staff) {
        initComponents();
        this.staff = staff;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtidstaff = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNoHp = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txtidatasan = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtJabatan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("MASUKKAN DATA STAFF");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 380, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ID Staff");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 70, 20));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("sansserif", 0, 8)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 153, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 50, 30));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("No HP");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 80, 20));

        txtidstaff.setBackground(new java.awt.Color(0, 0, 0));
        txtidstaff.setForeground(new java.awt.Color(204, 153, 255));
        txtidstaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidstaffActionPerformed(evt);
            }
        });
        jPanel1.add(txtidstaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 280, 30));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nama");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 80, 20));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("ID Atasan");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 80, 20));

        txtNoHp.setBackground(new java.awt.Color(0, 0, 0));
        txtNoHp.setForeground(new java.awt.Color(204, 153, 255));
        txtNoHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoHpActionPerformed(evt);
            }
        });
        jPanel1.add(txtNoHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 280, 30));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(204, 153, 255));
        jButton2.setText("INPUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 90, 30));

        txtidatasan.setBackground(new java.awt.Color(0, 0, 0));
        txtidatasan.setForeground(new java.awt.Color(204, 153, 255));
        txtidatasan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidatasanActionPerformed(evt);
            }
        });
        jPanel1.add(txtidatasan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 280, 30));

        txtNama.setBackground(new java.awt.Color(0, 0, 0));
        txtNama.setForeground(new java.awt.Color(204, 153, 255));
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 280, 30));

        txtJabatan.setBackground(new java.awt.Color(0, 0, 0));
        txtJabatan.setForeground(new java.awt.Color(204, 153, 255));
        txtJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJabatanActionPerformed(evt);
            }
        });
        jPanel1.add(txtJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 280, 30));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Jabatan");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 80, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Fancy/2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //        // TODO add your handling code here:
        this.setVisible(false);
        new Lihat(this.staff).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtidstaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidstaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidstaffActionPerformed

    private void txtNoHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoHpActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String idStaffText = txtidstaff.getText();
        

        try {
            String idStaff = txtidstaff.getText();
            String namaStaff = txtNama.getText();
            String NoHp = txtNoHp.getText();
            String Jabatan = txtJabatan.getText();
            String idAtasan = txtidatasan.getText();

            if (idAtasan.equals("")) {
            idAtasan = null;
            }
        
            // Membuat objek Staff dengan data yang ingin ditambahkan
            Staff staff = new Staff(idStaff, namaStaff, NoHp, Jabatan, idAtasan);

            // Memanggil metode Tambah untuk menambahkan data staff ke database
            boolean added = staff.Tambah();

            if (added) {
                JOptionPane.showMessageDialog(null, "Data staff berhasil ditambahkan.");
                this.setVisible(false);
                new Lihat(this.staff).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Gagal menambahkan data staff.");
            }
        } catch (NumberFormatException e) {
        // Tangani jika inputan ID Staff bukan bilangan bulat
        JOptionPane.showMessageDialog(null, "ID Staff harus berupa bilangan bulat.");
    }
    }


        private boolean isIdStaffValid(String Id_Staff, Connection conn) {
            try {
                String query = "SELECT * FROM staff WHERE Id_Staff = ?";
                PreparedStatement preparedStatement = conn.prepareStatement(query);
                preparedStatement.setString(1, Id_Staff);
                ResultSet result = preparedStatement.executeQuery();

                // Jika data dengan Id_SuperAdmin tersebut ditemukan, maka return true
                return result.next();
            } catch (SQLException ex) {
                return false;
            }
        }

        private boolean isNoKKValid(String No_KK, Connection conn) {
            try {
                String query = "SELECT * FROM keluarga WHERE No_KK = ?";
                PreparedStatement preparedStatement = conn.prepareStatement(query);
                preparedStatement.setString(1, No_KK);
                ResultSet result = preparedStatement.executeQuery();

                // Jika data dengan Id_SuperAdmin tersebut ditemukan, maka return true
                return result.next();
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
                return false;
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtidatasanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidatasanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidatasanActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJabatanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tambah(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtJabatan;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoHp;
    private javax.swing.JTextField txtidatasan;
    private javax.swing.JTextField txtidstaff;
    // End of variables declaration//GEN-END:variables
}
